### ISSUE TITLE
Unable to import ubuntu docker image

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/enroot#148]
I am unable to pull ubuntu docker image from docker hub; 

```
$ enroot import docker://ubuntu
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: <anonymous>
[INFO] Authentication succeeded
[INFO] Fetching image manifest list
[INFO] Fetching image manifest
[ERROR] URL https://registry-1.docker.io/v2/library/ubuntu/manifests/latest returned error code: 404 Not Found
```

```
$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
677076032cca: Pull complete 
Digest: sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
```

**Comment by flx42** [comment]
The Ubuntu images moved to using OCI image manifests instead of Docker image manifests a few days ago, so you now need this commit on the `master` branch: https://github.com/NVIDIA/enroot/commit/a7493bf44dd3c5e83d6732f39bdc711b963a1a69

You can also apply the patch @3XX0 provided in the release notes for 3.4.0: https://github.com/NVIDIA/enroot/releases/tag/v3.4.0
A new release will be done soon.

**Comment by itzsimpl** [comment]
That worked, thank you!

**Comment by krono** [comment]
Hey, @flx42 or @3XX0 could you maybe sticky this issue until the next release :)
