### ISSUE TITLE
is there any way to name enroot container so that the container could be filtered by enroot list -f easier?

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#33]
below are containers running on my machine:
[root@rcn04 ~]# enroot list -f
NAME    PID      STATE  STARTED  TIME      MNTNS       USERNS      COMMAND
ubuntu  1583996  S      05:08    01:51:13  4026532603  4026532602  /bin/sh /root/test/1597122491.2123
        **1588974  S      05:31    01:27:44  4026532606  4026532605  /bin/sh -c  sleep 22222222222222222
        1588979  S      05:31    01:27:44  4026532608  4026532607  /bin/sh -c  sleep 22222222222222222**

I cannot distinguish them except maintaining a container-pid map. 
Is there any option used to name the container like "docker run --name" ?

Thanks

**Comment by 3XX0** [comment]
Unfortunately no, Enroot is completely stateless so after the container is fired up the runtime is out of the picture and we can only list what is known to the system (i.e. the PID of the process and its rootfs).

I guess we could add something like `/proc/self/comm` to the list so that you could potentially tweak it from within the container but that's about it.
