### ISSUE TITLE
Build container from recipe file

### ISSUE THREAD

**Issue by AquaL1te** [NVIDIA/enroot#40]
Is it me, or is there no mention of building containers from a recipe file? It seems that enroot fully depends on container registries to import and run something? I can't build a container myself locally like with Singularity with the `--fakeroot` option and like Podman?  If that's incorrect, then please highlight in the [usage](https://github.com/NVIDIA/enroot/blob/master/doc/usage.md) as well, and in the main page with the [quick start overview](https://github.com/NVIDIA/enroot#enroot). Thanks.

**Comment by 3XX0** [comment]
Yes this is by design because there are better tools for building containers out there (`buildah`, `docker`, etc) which need to be privileged. Unprivileged use cases are pretty much limited since there is no way to do layering safely.

If you don't really care about layering and the advanced build mechanisms that these tools offer you can always use `enroot batch` and `enroot export` as your recipe. For example `enroot` itself is packaged this way: https://github.com/NVIDIA/enroot/blob/master/pkg/debbuild

It could be as simple as
```bash
mkdir -p ~/.local/share/enroot/ubuntu
curl http://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-base-20.04-base-amd64.tar.gz | tar -C $_ -xz
enroot batch myrecipe
enroot export -o myimage.sqsh ubuntu # or something like "tar czf myimage.tar.gz ~/.local/share/enroot/ubuntu"
```
Or alternatively from a Docker image
```bash
enroot import docker://ubuntu
enroot create ubuntu.sqsh
enroot batch myrecipe
enroot export -o myimage.sqsh ubuntu
```

Where `myrecipe` is something like:
```bash
#ENROOT_REMAP_ROOT=y
#ENROOT_ROOTFS_WRITABLE=y
#ENROOT_ROOTFS=ubuntu

rc() {
    apt get ...
}
```
