### ISSUE TITLE
RFE: import local docker image

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/enroot#7]
It'd be cool if I could import a local docker image with enroot. Maybe something like this?
```
docker build -t my-tmp-image .
enroot import docker:///my-tmp-image
```
Or maybe there's a way to trick enroot into using my local daemon as a registry somehow?

**Comment by lukeyeager** [comment]
This hack works for now:
```
docker run -d -p 5000:5000 --name registry registry:2
docker build -t "$img" .
reg_img="localhost:5000/$USER/$img"
enroot_uri="localhost:5000#$USER/$img"
docker tag "$img" "$reg_img"
docker push "$reg_img"
ENROOT_ALLOW_HTTP=yes enroot import "docker://$enroot_uri"
```
FYI if I don't add the `$USER` prefix, then I get this error:
```
+ enroot import --output tmp.sqsh docker://localhost:5000#tmp:2
[INFO] Querying registry for permission grant
[ERROR] URL http://localhost:5000/v2/library/tmp/manifests/2 returned error code: 404
```

**Comment by 3XX0** [comment]
Yeah, I thought about it but it adds a lot complexity in the docker import since the docker daemon API is not exactly the same as Registry V2.

Some alternatives are:
* A local registry (like you did) 
* Use skopeo+umoci, although you'll probably lose some information from the image (e.g. `ENV`, `WORKDIR`, `CMD`, etc)
* Use `docker export` inside `ENROOT_DATA_PATH`, but it has the same downsides as above

Maybe we could rely on `docker save` somehow, I forgot how the format looks like exactly.
Another approach would be to expose [docker::_configure](https://github.com/NVIDIA/enroot/blob/master/src/docker.sh#L145), so you could do something like `docker inspect img | enroot genconf`

**Comment by 3XX0** [comment]
Closing as there is now a way to do it in master

**Comment by lukeyeager** [comment]
Confirmed. With the latest code:
```console
$ cat Dockerfile 
FROM alpine
$ docker build -t tmp .
$ enroot import dockerd://tmp
$ enroot start tmp.sqsh grep PRETTY /etc/os-release
PRETTY_NAME="Alpine Linux v3.10"
```
